modded class CassetteBase_SSS extends ItemBase
{
	override void Init()
	{
		super.Init();
		m_TrackLenghts.Insert(new Param3<int, int, int>(1, 1, 171));
		m_TrackLenghts.Insert(new Param3<int, int, int>(1, 2, 249));
		m_TrackLenghts.Insert(new Param3<int, int, int>(1, 3, 290));
		m_TrackLenghts.Insert(new Param3<int, int, int>(1, 4, 305));
		m_TrackLenghts.Insert(new Param3<int, int, int>(1, 5, 217));
		m_TrackLenghts.Insert(new Param3<int, int, int>(1, 6, 161));
		m_TrackLenghts.Insert(new Param3<int, int, int>(1, 7, 241));
		m_TrackLenghts.Insert(new Param3<int, int, int>(1, 8, 306));
		m_TrackLenghts.Insert(new Param3<int, int, int>(1, 9, 226));
		m_TrackLenghts.Insert(new Param3<int, int, int>(1, 10, 215));
		m_TrackLenghts.Insert(new Param3<int, int, int>(2, 1, 209));
		m_TrackLenghts.Insert(new Param3<int, int, int>(2, 2, 195));
		m_TrackLenghts.Insert(new Param3<int, int, int>(2, 3, 204));
		m_TrackLenghts.Insert(new Param3<int, int, int>(2, 4, 216));
		m_TrackLenghts.Insert(new Param3<int, int, int>(2, 5, 204));
		m_TrackLenghts.Insert(new Param3<int, int, int>(2, 6, 223));
		m_TrackLenghts.Insert(new Param3<int, int, int>(2, 7, 248));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 1, 231));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 2, 205));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 3, 210));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 4, 162));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 5, 194));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 6, 173));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 7, 189));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 8, 164));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 9, 219));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 10, 209));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 11, 259));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 12, 268));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 13, 185));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 14, 184));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 15, 201));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 16, 143));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 17, 213));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 18, 205));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 19, 203));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 20, 199));
		m_TrackLenghts.Insert(new Param3<int, int, int>(3, 21, 196));
		m_TrackLenghts.Insert(new Param3<int, int, int>(4, 1, 166));
		m_TrackLenghts.Insert(new Param3<int, int, int>(4, 2, 162));
		m_TrackLenghts.Insert(new Param3<int, int, int>(4, 3, 173));
		m_TrackLenghts.Insert(new Param3<int, int, int>(4, 4, 206));
		m_TrackLenghts.Insert(new Param3<int, int, int>(5, 1, 244));
		m_TrackLenghts.Insert(new Param3<int, int, int>(5, 2, 255));
		m_TrackLenghts.Insert(new Param3<int, int, int>(5, 3, 222));
		m_TrackLenghts.Insert(new Param3<int, int, int>(5, 4, 155));
		m_TrackLenghts.Insert(new Param3<int, int, int>(5, 5, 192));
		m_TrackLenghts.Insert(new Param3<int, int, int>(5, 6, 129));
		m_TrackLenghts.Insert(new Param3<int, int, int>(6, 1, 298));
		m_TrackLenghts.Insert(new Param3<int, int, int>(6, 2, 260));
		m_TrackLenghts.Insert(new Param3<int, int, int>(6, 3, 233));
		m_TrackLenghts.Insert(new Param3<int, int, int>(6, 4, 253));
		m_TrackLenghts.Insert(new Param3<int, int, int>(6, 5, 232));
		m_TrackLenghts.Insert(new Param3<int, int, int>(6, 6, 264));
		m_TrackLenghts.Insert(new Param3<int, int, int>(6, 7, 269));
		m_TrackLenghts.Insert(new Param3<int, int, int>(6, 8, 318));
		m_TrackLenghts.Insert(new Param3<int, int, int>(7, 1, 257));
		m_TrackLenghts.Insert(new Param3<int, int, int>(7, 2, 248));
		m_TrackLenghts.Insert(new Param3<int, int, int>(7, 3, 317));
		m_TrackLenghts.Insert(new Param3<int, int, int>(7, 4, 243));
		m_TrackLenghts.Insert(new Param3<int, int, int>(7, 5, 233));
		m_TrackLenghts.Insert(new Param3<int, int, int>(7, 6, 240));
		m_TrackLenghts.Insert(new Param3<int, int, int>(7, 7, 247));
		m_TrackLenghts.Insert(new Param3<int, int, int>(7, 8, 204));
		m_TrackLenghts.Insert(new Param3<int, int, int>(7, 9, 230));
	}
};